### ISSUE TITLE
ModuleNotFoundError                       

### ISSUE THREAD

**Issue by TolgaCorbaci** [volkamerlab/teachopencadd#100]
Binder talktorials cannot find and import the module
![image](https://user-images.githubusercontent.com/53476453/117189717-2c775200-ade7-11eb-9273-593c2b4c30b3.png)

**Comment by dominiquesydow** [comment]
Hi @TolgaCorbaci, I can reproduce this problem - thanks for reporting (example here: T007). We will investigate and get back to you.

**Comment by dominiquesydow** [comment]
@jaimergp, this might happen because we have moved the `environment.yml` file from the repo root to `devtools/` so that Binder cannot find any installation instructions any more?

**Comment by jaimergp** [comment]
Oops, yes, my fault. I'll revert today, sorry.

**Comment by jaimergp** [comment]
@TolgaCorbaci, thanks for the report! It should be fixed now. If you can please check, we can consider this as solved then!

**Comment by jaimergp** [comment]
Oops, maybe it's not... 😬 One second!

**Comment by jaimergp** [comment]
Ok, _now_ :D

**Comment by TolgaCorbaci** [comment]
Problem seems to be solved, thank you so much guys, appreciate it.
