### ISSUE TITLE
T014: ccp4 visualization with nglview broken?

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#103]
#### Summary
Note: This bug is not on our end.
Volumes in `nglview` are currently not visualized in Jupyter Lab (you can look at them with Jupyter Notebook though).

#### Where?
https://nbviewer.jupyter.org/github/volkamerlab/teachopencadd/blob/t011-base/teachopencadd/talktorials/T014_binding_site_detection/talktorial.ipynb
Cell 18

**Comment by jaimergp** [comment]
Is this still pending?

**Comment by dominiquesydow** [comment]
Yes.

**Comment by dominiquesydow** [comment]
Minimal example:

```
selected_pocket_volume_url = 'https://proteins.plus/results/dogsite/DULB3XTM1tDVFafpkvYcAXJM/3w32_P_0_0_gpsAll.ccp4.gz'

r = requests.get(selected_pocket_volume_url)
r.raise_for_status()
# Decompress response content and wrap it in a file-like object
memfile = io.BytesIO(gzip.decompress(r.content))

viewer = nglview.show_pdbid(pdb_id)
# Since we are passing bytes with no path or extension
# we need to tell nglview what kind of data this is: ccp4
viewer.add_component(memfile, ext="ccp4")
viewer.center()
viewer
```
Will not show the volume anymore:
![image](https://user-images.githubusercontent.com/7207093/118480622-c5c13500-b712-11eb-8298-d4a701d91fb1.png)

Notebook runs without errors.

**Comment by jaimergp** [comment]
Console shows `error loading file: 'RangeError: Invalid typed array length: 56'`

**Comment by jaimergp** [comment]
Possibly related: https://github.com/nglviewer/nglview/issues/975

**Comment by jaimergp** [comment]
PyMol does work with the same file, so it's definitely on NGLView's side:

![image](https://user-images.githubusercontent.com/2559438/118485830-2d7a7e80-b719-11eb-8b2a-d0165b51989e.png)

**Comment by dominiquesydow** [comment]
Since this is still pending, I added a note to the talktorial that the volume is visible with Jupyter Notebook (not Lab).
