### ISSUE TITLE
Docs not synced with `master`?

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#105]
Docs are not synced with `master` branch.

We have the latest installation link on [`master`](https://github.com/volkamerlab/teachopencadd/blob/master/docs/installing.rst): https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml

But the deprecated installation link still shows up on the [website](https://projects.volkamerlab.org/teachopencadd/installing.html):
https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/environment.yml

I cannot find the RTD (?) builts for the TeachOpenCADD website, @jaimergp, could you please point me to them? Thank you!

**Comment by jaimergp** [comment]
We don't deploy to Read the docs, but to GH Pages thorugh the CI pipeline in GH Actions. See logs [here](https://github.com/volkamerlab/teachopencadd/runs/2516791859). There's an issue with some objects that I think I fixed in the mega PR.

**Comment by dominiquesydow** [comment]
Hi @jaimergp, could you please point me to the fix mentioned in your command before?

**Comment by dominiquesydow** [comment]
Linked to #129

**Comment by dominiquesydow** [comment]
Docs are passing and the website therefore in sync again :)
