### ISSUE TITLE
T008: Align Complexes doesn't work

### ISSUE THREAD

**Issue by Carlbullish** [volkamerlab/teachopencadd#108]
I am also having issues with this line could this be checked into? i tried using jupyter notebooks and google colab but still couldn't get around it

results = align(complexes, method=METHODS["mda"])

this is the error i keep getting when i run the code
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_2872/2813988720.py in <module>
----> 1 results = align(complexes, method=METHODS["mda"])

~\anaconda3\envs\introductiontopython\lib\site-packages\opencadd\structure\superposition\api.py in align(structures, method, **kwargs)
     40     results = []
     41     for mobile in mobiles:
---> 42         result = aligner.calculate([reference, mobile])
     43         results.append(result)
     44 

~\anaconda3\envs\introductiontopython\lib\site-packages\opencadd\structure\superposition\engines\base.py in calculate(self, structures, *args, **kwargs)
     29         """
     30         assert len(structures) == 2
---> 31         return self._calculate(structures, *args, **kwargs)
     32 
     33     def _calculate(self, structures, *args, **kwargs):

~\anaconda3\envs\introductiontopython\lib\site-packages\opencadd\structure\superposition\engines\mda.py in _calculate(self, structures, *args, **kwargs)
    117 
    118         # Get matching atoms
--> 119         selection, alignment = self.matching_selection(*structures)
    120         ref_atoms = ref_universe.select_atoms(selection["reference"])
    121         mobile_atoms = mob_universe.select_atoms(selection["mobile"])

~\anaconda3\envs\introductiontopython\lib\site-packages\opencadd\structure\superposition\engines\mda.py in matching_selection(self, reference, mobile)
    176             fasta["ref"], fasta["mob"], *_empty = alignment.get_gapped_sequences()
    177             fasta.write("temp.fasta")
--> 178             selection = fasta2select(
    179                 "temp.fasta",
    180                 ref_resids=ref_resids,

~\anaconda3\envs\introductiontopython\lib\site-packages\opencadd\structure\superposition\sequences.py in fasta2select(fastafilename, ref_resids, ref_segids, target_resids, target_segids, backbone_selection)
    115 
    116     """
--> 117     protein_gapped = Bio.Alphabet.Gapped(Bio.Alphabet.IUPAC.protein)
    118     with open(fastafilename) as fasta:
    119         alignment = Bio.AlignIO.read(fasta, "fasta", alphabet=protein_gapped)

AttributeError: module 'Bio' has no attribute 'Alphabet'

**Comment by jaimergp** [comment]
Hi! 

I recall this is an issue with the version of `biopython` installed in your environment. As a workaround, you need to make sure its version is `biopython<=1.77`.

**Comment by Carlbullish** [comment]
Thank you Jaime.

> Hi!
> 
> I recall this is an issue with the version of `biopython` installed in your environment. As a workaround, you need to make sure its version is `biopython<=1.77`.

Thank you Jaime
