### ISSUE TITLE
T015_protein_ligand_docking Using OPAL Attribute error: Nonetype object has no attribute atttrs

### ISSUE THREAD

**Issue by Carlbullish** [volkamerlab/teachopencadd#111]
When i run the code below:

%time result = step_03_opal(PROTEIN, smiles[:1], COMPLEX)

i get the following error:
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~\AppData\Local\Temp/ipykernel_6344/2733412323.py in step_03_opal(protein, smiles, pdbcomplex)
     14     """
     15     prepared_protein = opal_prepare_protein(protein)
---> 16     center, radius = dogsite_scorer_guess_binding_site(pdbcomplex)
     17     size = [radius] * 3  # Vina supports non-cubic boxes, but we will use a cube for simplicity
     18     for i, smile in enumerate(smiles):

~\AppData\Local\Temp/ipykernel_6344/3358257068.py in dogsite_scorer_guess_binding_site(protein)
    131         job_location = dogsite_scorer_submit_with_pdbid(protein)
    132     elif protein.endswith(".pdb"):
--> 133         job_location = dogsite_scorer_submit_with_custom_pdb(protein)
    134     else:
    135         raise ValueError("`protein` must be a PDB ID or a path to a .pdb file!")

~\AppData\Local\Temp/ipykernel_6344/3358257068.py in dogsite_scorer_submit_with_custom_pdb(pdbfile)
     78     # 2. Get internal location id
     79     html = BeautifulSoup(r.text)
---> 80     pdb_id = html.find("input", {"name": "dogsite[pdbCode]"}).attrs["value"]
     81 
     82     # 3. Get the internal job ID

AttributeError: 'NoneType' object has no attribute 'attrs'

I hope you don't mind my many issues. Im really trying to understand and see how i can make maximum use of these talktorials in my current research work. 
Thansk and cheers for the good work! @dominiquesydow and @jaimergp and the whole Volkamerlab team

**Comment by AndreaVolkamer** [comment]
@Carlbullish can you tell us which PR you are using. Because in the newest [T015](https://github.com/volkamerlab/teachopencadd/blob/t011-base/teachopencadd/talktorials/T015_protein_ligand_docking/talktorial.ipynb), we moved away from OPAL and are using smina as docking engine. The functioning notebook additions are all in [PR #74](https://github.com/volkamerlab/teachopencadd/pull/74) in the  [T011-base](https://github.com/volkamerlab/teachopencadd/tree/t011-base) branch.
Tagging @schallerdavid here also, who reworked T015.

**Comment by Carlbullish** [comment]
Hi @AndreaVolkamer. Thanks . i got to find the newest T015, I still ran into an issue when i tried to use smina This is the code below:
output_text = run_smina(
    DATA / "ligand.pdbqt",
    DATA / "protein.pdbqt",
    DATA / "docking_poses.sdf",
    pocket_center,
    pocket_size,
)
print(output_text)

The error i get :

FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8688/2258732981.py in <module>
----> 1 output_text = run_smina(
      2     DATA / "ligand.pdbqt",
      3     DATA / "protein.pdbqt",
      4     DATA / "docking_poses.sdf",
      5     pocket_center,

~\AppData\Local\Temp/ipykernel_8688/2585986300.py in run_smina(ligand_path, protein_path, out_path, pocket_center, pocket_size, num_poses, exhaustiveness)
     27         The output of the Smina calculation.
     28     """
---> 29     output_text = subprocess.check_output(
     30         [
     31             "smina",

~\anaconda3\envs\introductiontopython\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    413         kwargs['input'] = empty
    414 
--> 415     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    416                **kwargs).stdout
    417 

~\anaconda3\envs\introductiontopython\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    491         kwargs['stderr'] = PIPE
    492 
--> 493     with Popen(*popenargs, **kwargs) as process:
    494         try:
    495             stdout, stderr = process.communicate(input, timeout=timeout)

~\anaconda3\envs\introductiontopython\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    856                             encoding=encoding, errors=errors)
    857 
--> 858             self._execute_child(args, executable, preexec_fn, close_fds,
    859                                 pass_fds, cwd, env,
    860                                 startupinfo, creationflags, shell,

~\anaconda3\envs\introductiontopython\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1309             # Start the process
   1310             try:
-> 1311                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1312                                          # no special security
   1313                                          None, None,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Carlbullish** [comment]
I figured it out! You need to add 
conda install -c conda-forge smina

to the opening import library section :). So that learners like me know that having it installed is necessary to get the dock output. Thanks

**Comment by dominiquesydow** [comment]
Hi @Carlbullish, 

In order to have less troubles with missing packages, I recommend to install a `conda` environment with all packages needed for the `t011-base` branch:

```bash
# Change to your TeachOpenCADD directory
cd path/to/TeachOpenCADD
# Checkout t011-base branch
git checkout t011-base
# Create the environment
conda env create -f devtools/test_env.yml -n teachopencadd
# Activate the environment
conda activate teachopencadd
# Start notebooks within the activated environment
jupyter lab  # or jupyter notebook
```
