### ISSUE TITLE
T008: PDB API for chemicals changed

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#124]
The PDB API changed again and may not be updated in `biotite`.

Talktorial T008 throws the following error (cell 9):
```
RequestError: Error 400: Invalid request to the [ text ] service: search is not enabled on [ chem_comp.formula_weight ] attribute
```
As far as I understand they split the Search Service from `text` into `text` and `text_chem`:
https://search.rcsb.org/#search-services

They split the search attribute web pages (needs updating in the talktorial as well)
- https://search.rcsb.org/chemical-search-attributes.html
- https://search.rcsb.org/structure-search-attributes.html

The old API (I think):
```
{
  "query": {
    "type": "terminal",
    "service": "text",
        "parameters": {
          "attribute": "chem_comp.formula_weight",
          "operator": "greater",
          "value": 100
        }
  },
  "return_type": "entry"
}
```

The new API
```
{
  "query": {
    "type": "terminal",
    "service": "text_chem",
        "parameters": {
          "attribute": "chem_comp.formula_weight",
          "operator": "greater",
          "value": 100
        }
  },
  "return_type": "entry"
}
```

**Comment by Carlbullish** [comment]
Hi @dominiquesydow , so please how can we get the issue resolved?

**Comment by dominiquesydow** [comment]
Hi @Carlbullish,

We are currently waiting for `biotite` to cut a new `conda` release, which should happen this week:
https://github.com/biotite-dev/biotite/issues/347#issuecomment-907117669

In that case, a simple `conda update biotite` should be enough. I will comment here when this happened.

If you want to get started earlier, please remove your `biotite` `conda` installation and `pip` install the latest `biotite` release from GitHub:

```
# in your teachopencadd conda environment
conda remove biotite
pip install https://github.com/biotite-dev/biotite/archive/master.zip
```

If you still get the error above, the new version is not installed, yet - and I recommend to create a fresh conda environment where you install `biotite` with `pip` directly (plus all packages needed for T008).

My apologies for the inconvenience; I hope the PDB API will stay as-is for a while now. On the plus side, the `biotite` maintainers reacted super quickly with an update - big thanks to them!

**Comment by Carlbullish** [comment]
> Hi @Carlbullish,
> 
> We are currently waiting for `biotite` to cut a new `conda` release, which should happen this week:
> [biotite-dev/biotite#347 (comment)](https://github.com/biotite-dev/biotite/issues/347#issuecomment-907117669)
> 
> In that case, a simple `conda update biotite` should be enough. I will comment here when this happened.
> 
> If you want to get started earlier, please remove your `biotite` `conda` installation and `pip` install the latest `biotite` code from GitHub:
> 
> ```
> # in your teachopencadd conda environment
> conda remove biotite
> pip install https://github.com/biotite-dev/biotite/archive/master.zip
> ```
> 
> If you still get the error above, the new version is not installed, yet - and I recommend to create a fresh conda environment where you install `biotite` with `pip` directly (plus all packages needed for T008).
> 
> My apologies for the inconvenience; I hope the PDB API will stay as-is for a while now. On the plus side, the `biotite` maintainers reacted super quickly with an update - big thanks to them!

Thanks a lot @dominiquesydow .. I look forward to it. I guess i will wait for the update then. 

And if you dont mind me asking, running the binder for talktorial 10 and other talktorials afterwards, is not yet implemented for successful execution as compared to talktorial 1 - talktorial 10?

**Comment by dominiquesydow** [comment]
Hi @Carlbullish,

Great, I'll keep you posted.

Regarding

> And if you dont mind me asking, running the binder for talktorial 10 and other talktorials afterwards, is not yet implemented for successful execution as compared to talktorial 1 - talktorial 10?

Please see https://github.com/volkamerlab/teachopencadd/issues/130; thanks for putting this on my map!

**Comment by Carlbullish** [comment]
Thanks @dominiquesydow , i'll keep tabs with progress made too.

**Comment by dominiquesydow** [comment]
Please try out the latest version of T008 on the `master` branch.
