### ISSUE TITLE
Installing TeachOpenCADD on google colab

### ISSUE THREAD

**Issue by andresilvapimentel** [volkamerlab/teachopencadd#129]
I am trying to install TeachOpenCADD on google colab using the instruction in the web page:

https://projects.volkamerlab.org/teachopencadd/installing.html

After installing conda in the notebook, the command below gives the following error:

!conda env create -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/environment.yml

CondaHTTPError: HTTP 404 NOT FOUND for url <https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/environment.yml>
Elapsed: 00:00.133251

An HTTP error occurred when trying to retrieve this URL.
The URL does not exist.

Could you give the right URL, please?

I cannot import the packages from teachopencadd. Thanks.

**Comment by dominiquesydow** [comment]
Hi @andresilvapimentel,

Thank you for bringing this up!

Can you please try: 
https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml

**Comment by andresilvapimentel** [comment]
Dear Dominique,
I did install the conda enviroment, but I could not run the teachopencadd as requested for testing following the instructions on https://projects.volkamerlab.org/teachopencadd/installing.html

The google colab could not find the teachopencadd package.

Do you know what is going on? Here is what I did on google colab:

! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

!wget https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml

!conda env create -f users_env.yml

!conda activate teachopencadd

from teachopencadd.utils import seed_everything
seed_everything()  # fix seed to get deterministic outputs

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-638d3643d896> in <module>()
----> 1 from teachopencadd.utils import seed_everything
      2 
      3 seed_everything()  # fix seed to get deterministic outputs

ModuleNotFoundError: No module named 'teachopencadd'

**Comment by dominiquesydow** [comment]
@jaimergp can you help out with this Google Colab question?

I get the TeachOpenCADD environment installed but I am unsure how to activate it

```
!pip install condacolab
import condacolab
condacolab.install()
!mamba install -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml -n toc
```

**Comment by jaimergp** [comment]
Colab runs a Python process already, so we need to stay with the `base` environment. If you want to install stuff from a YML, `update` it after the kernel restart (separate cell).

```
!mamba env update -n base -f environment.yml
```

**Comment by andresilvapimentel** [comment]
When I run the mamba by using:

!pip install condacolab
import condacolab
condacolab.install()
!mamba install -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml -n toc

I get the error: EnvironmentLocationNotFound: Not a conda environment: /usr/local/envs/toc

So, it does not work it...

**Comment by jaimergp** [comment]
You need to run these code blocks in two different cells:

First cell:

```
!pip install condacolab
import condacolab
condacolab.install()
```

Execute it and wait for the kernel to restart.

Second cell:

```
!mamba env update -n base -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml 
```

Run it and then, in a third cell, you can import the packages.

**Comment by andresilvapimentel** [comment]
Thanks.
It works!!!

Em seg., 6 de set. de 2021 às 12:06, Jaime Rodríguez-Guerra <
***@***.***> escreveu:

**Comment by arya-blip** [comment]
I get error 404

**Comment by Ash100** [comment]
Hello, I want to use T005 (Clustering) tutorial. I tried all of the above steps but so far no success. Would any one help me out how can and what scripts should I use in Google colab notebook, to install and activate the said environment.
Best Regards

**Comment by andresilvapimentel** [comment]
@dominiquesydow The installation procedure described above stopped running on google colab. Can you help me fixing this issue, please?
All the best. Thanks.
