### ISSUE TITLE
Include new talktorials to binder setup

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#130]
Upon merge of #74 make sure new talktorials run with binder setup; add notes to those that may not run there (e.g. MD simulation).

---

This issue is prompted by @Carlbullish's question in https://github.com/volkamerlab/teachopencadd/issues/124#issuecomment-909398622:

> And if you dont mind me asking, running the binder for talktorial 10 and other talktorials afterwards, is not yet implemented for successful execution as compared to talktorial 1 - talktorial 10?

- [Resolved, see comments below] Talktorial 010 seems to run fine on Binder; @Carlbullish, did you run into troubles
- Talktorials >010 will be included in Binder once we fixed some final technical issues in #74

**Comment by Carlbullish** [comment]
@dominiquesydow . I didn't run into any trouble actually, Getting a choice Ligand to Query with enough PDB complexes to use was actually my issue. Imatinib happens to have quite a number of these complexes compared to other ligands i have been trying to work with

**Comment by Carlbullish** [comment]
Thanks for the good job you all are doing.

**Comment by dominiquesydow** [comment]
The new notebooks (>T010) are running on Binder; please re-open this issue if you run into troubles.
