### ISSUE TITLE
T019: No openmmforcefields under Windows

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#136]
T019 does not run under Windows.

Our CI fails with: `ModuleNotFoundError: No module named 'openff'`

#### Why? 

https://github.com/volkamerlab/teachopencadd/blob/d1e92f454e84045e92caa718211d9c528790ca0f/devtools/test_env.yml#L30-L32

See also here: https://github.com/volkamerlab/teachopencadd/pull/74#issuecomment-842160547

`openmmforcefields` may cause the problem, check progress of this issue: https://github.com/openmm/openmmforcefields/issues/163

#### Do we notify users?
Yes, talktorial contains disclaimer, linking back to this issue:
> Also, note that this talktorial **will not run on Windows** for the time being (check progress in [this issue](https://github.com/volkamerlab/teachopencadd/issues/136)).

#### What do we do regarding our CI?
Remove the T019 from the Windows CI.
- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
- https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os

**Comment by Carlbullish** [comment]
Thanks @dominiquesydow for your efforts.. I do hope this issue gets resolved.
