### ISSUE TITLE
Open tasks for version 2021.1

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#137]
Open tasks for the v2.0.0 release (after the merge of #74):

- [x] Make sure Binder runs #130 (maybe in another PR after this one?)
- [x] Website: https://github.com/volkamerlab/teachopencadd/issues/105
- [x] T018: Add a disclaimer that notebook is not ready yet: https://github.com/volkamerlab/teachopencadd/pull/142
- [x] T018: Add talktorial: #125 
- [x] Add new tag v2.0.0
- [x] Fix conda packaging; add package to conda-forge
- [x] Website: https://github.com/volkamerlab/teachopencadd/issues/143
- [x] Website: https://github.com/volkamerlab/teachopencadd/issues/141
- [x] Website: Update talktorial collections: https://projects.volkamerlab.org/teachopencadd/talktorials.html https://github.com/volkamerlab/teachopencadd/pull/161
- [x] Cut the release
- [x] Update the cf package

**Comment by dominiquesydow** [comment]
### Conda packaging - TODOs

- [ ] Add `autodocktools-prepare-py3k` to `conda`: https://github.com/volkamerlab/teachopencadd/blob/dd540f531cefe69f4754e276d271eac1e97395e1/devtools/test_env.yml#L50
- [ ] Add `opencadd` to `conda`: https://github.com/volkamerlab/teachopencadd/blob/dd540f531cefe69f4754e276d271eac1e97395e1/devtools/test_env.yml#L51
- [ ] Submit `teachopencadd` package to `conda-forge`; use conda-recipe? https://github.com/volkamerlab/teachopencadd/blob/t011-base/devtools/conda-recipe/meta.yaml
- [ ] What does this CI bit do? https://github.com/volkamerlab/teachopencadd/blob/a27f702e9b690f8556bce711ccebe42451b1ff82/.github/workflows/ci.yml#L109-L146

**Comment by jaimergp** [comment]
> Submit teachopencadd package to conda-forge; use conda-recipe?

Yes, we might need to adapt some bits for cf, but most of the recipe is already there.

> What does this CI bit do?

It builds the recipe locally, to ensure that our `meta.yaml` is still in good shape.

And yes, at least OpenCADD needs to be added to conda-forge. Autodocktools Prepare can be left outside and we just pip-install it in the relevant notebooks (it's a fork of an unmaintained project, makes little sense to package that sensibly).
