### ISSUE TITLE
T016: Nitrogen is recognized differently on Windows vs. Unix

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#138]
#### CI error message

```
[gw0] win32 -- Python 3.6.13 C:\Miniconda\envs\teachopencadd\python.exe
Notebook cell execution failed
Cell 15: Cell outputs differ

Input:
create_df_from_binding_site(interactions_by_site[selected_site], interaction_type="hbond")
# NBVAL_CHECK_OUTPUT

Traceback:
 mismatch 'text/html'

 assert reference_output == test_output failed:

  '<div>\n<styl...able>\n</div>' == '<div>\n<styl...able>\n</div>'
  Skipping 1084 identical leading characters in diff, use -v to show
  -      <td>N2</td>
  ?           ^
  +      <td>Nar</td>
  ?           ^^
          <td>(13.371, 34.064, 15.005)</td>
          <td>(10.667, 33.654, 16.145)</td>
        </tr>
      </tbody>
    </table>
    </div>
```
#### Why?

> T016: it fails due to a diff issue. A nitrogen is recognized differently on Windows than Unix (?). Might have to do with different versions installed.

From https://github.com/volkamerlab/teachopencadd/pull/74#issuecomment-842287171

> OpenBabel is used to identify hydrogen bond donor and acceptor atoms. Halogen atoms are excluded from this group and treated separately (see below).

From https://plip-tool.biotec.tu-dresden.de/plip-web/plip/help

Atom types in OpenBabel:
```
EXTTYP  [n]         Nar
EXTTYP  [$(N=*)]        N2
```
From https://github.com/openbabel/openbabel/blob/master/data/atomtyp.txt

**Comment by dominiquesydow** [comment]
OpenBabel seems to recognize the nitrogen 2373 in PDB 3poz differently under Windows and Unix; we will remove our nbval check from this cell for now and contact the maintainers.

Add the nbval check back if the issue gets solved.

**Comment by schallerdavid** [comment]
Issue raised on OpenBabel [#2409](https://github.com/openbabel/openbabel/issues/2409)
