### ISSUE TITLE
Anaconda versions?

### ISSUE THREAD

**Issue by davidlmobley** [volkamerlab/teachopencadd#14]
The main README.md refers to testing with anaconda2 (python 2.x?) but the environment.yml requires python > 3.6 if I'm reading it correctly. Maybe the README is out of date?

In this day and age I'd highly recommend making sure everything uses python 3.

**Comment by jaimergp** [comment]
Hi David, thanks for the feedback! I'm all in for dropping Python 2 altogether!

We are planning an update soon where we fix these inconsistencies. We have to get rid of our PyMol dependencies first (see #10), and then we will work on providing `conda`-installable packages. We'll keep you posted!
