### ISSUE TITLE
Issue on T009 · Ligand-based pharmacophores

### ISSUE THREAD

**Issue by andresilvapimentel** [volkamerlab/teachopencadd#147]
The command feature_factory = AllChem.BuildFeatureFactory(str(Path(RDConfig.RDDataDir) / "BaseFeatures.fdef")) is not working. It gives the error message:

```
OSError                                   Traceback (most recent call last)
<ipython-input-17-9f1fb722f467> in <module>()
----> 1 feature_factory = AllChem.BuildFeatureFactory(str(Path(RDConfig.RDDataDir) / "BaseFeatures.fdef"))

OSError: File: /opt/anaconda1anaconda2anaconda3/share/RDKit/Data/BaseFeatures.fdef could not be opened.
```

It solved with the command `feature_factory = os.path.join(RDConfig.RDDataDir,'BaseFeatures.fdef')`
but the following command also gives an error message:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-21-3c1dd36efe52> in <module>()
----> 1 features = feature_factory.GetFeaturesForMol(str(example_molecule))
      2 print(f"Number of features found: {len(features)}")

AttributeError: 'str' object has no attribute 'GetFeaturesForMol'

The command list(feature_factory.GetFeatureDefs().keys()) also gives the error message:

AttributeError                            Traceback (most recent call last)
<ipython-input-18-d24aee5309ac> in <module>()
----> 1 list(feature_factory.GetFeatureDefs().keys())

AttributeError: 'str' object has no attribute 'GetFeatureDefs'
```

Please, help me solving these issues. Thanks.

**Comment by dominiquesydow** [comment]
Hi @andresilvapimentel, since I cannot reproduce this error locally either, could you please also rerun this notebook with the new environment as described in https://github.com/volkamerlab/teachopencadd/issues/148?

Please ping me again, if the new environment does not resolve the problem, then I'll think of something new :)

**Comment by andresilvapimentel** [comment]
Solved!!! Thanks.
