### ISSUE TITLE
Timestamp DB queries for input data consistency

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/TeachOpenCADD#17]
If we query the databases often, the input data will change each time (specially with T1), so all the downstream notebooks will be slightly modified. We could filter out data after an arbitrary date (let's say 1/1/2020) to reduce this noise.

When this is addressed, make sure to review the text parts where some output is mentioned (as in "the first result shows a molecule named X").

**Comment by dominiquesydow** [comment]
We solved this problem in PR #8 where we filter fetched bioactivity data by bioactivity IDs from ChEMBL 27 release.
