### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by PARODBE** [volkamerlab/teachopencadd#171]
Hi everyone!

I am trying to reproduce your code of : https://projects.volkamerlab.org/teachopencadd/talktorials/T008_query_pdb.html

But I have a problem with: results = align(complexes, method=METHODS["mda"])

Because it requiere that biopython contains alphabet and in this version have been removed, I have tried downgrade at 1.77 version of biopython but it doesn't work for me.

Could you help me please??

Thanks
Pablo

**Comment by dominiquesydow** [comment]
Hi @PARODBE,

Thanks for your report! Could you please help us and post the following:

- From where you are running the notebook (local Jupyter Lab, Binder, Google Colab)?
- How did you install the environment needed for the talktorials?
- Could you please print the full error message _incl. code cell_ (should be cell 30).

**Comment by PARODBE** [comment]
Finally, I have got solve the problem, downgrade the biopython has worked, I don't understand the reason why at the beginning not. 

I am working on local jupyter notebook.

I have reading your another notebook doing docking, and I am having some problems installing openbabel for windows, I can installing the gui obviously, but for run in python? I have downloades the tar.gz and I have done python setup.py install but It doesn't work for me. Could you help me please? It is for run your notebook.

Thanks!

**Comment by dominiquesydow** [comment]
Great, happy to hear you got the notebook to run!!

Regarding the second installation question:
Have you installed the conda environment using:

```
mamba env create -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml -n teachopencadd2
# or (we do recommend mamba though since it is so much faster)
conda env create -f https://raw.githubusercontent.com/volkamerlab/TeachOpenCADD/master/devtools/other-conda-envs/users_env.yml -n teachopencadd2
```

If not - could you please try and let me know if you have still problems?

**Comment by PARODBE** [comment]
Uoooo so so useful!!!! Thank you so so much! Now you have a fan of your repository! haha 

By the way, this would be more a debate that a question. Normally for predict endpoints (classification or regression problems doesn't matter), you use as a input, 2d descriptors of RDKIT or fingerprints, and I know that it is possible to obtain 3D information with rdkit and Also there are another libraries for obtaining fingerprints 3d. But for example with pharmacophore information and MDAanalysis that you work in your notebooks, for complement the information that previously I said you. what variables would you add (related with your notebooks of MDAanalysis and pharmacophore)? It is possible that the ML or DL models don't improve but It would be interesting check it...

**Comment by dominiquesydow** [comment]
> Uoooo so so useful!!!! Thank you so so much! Now you have a fan of your repository! haha

Yay, that is wonderful!!!

The full installation instructions are on our website
https://projects.volkamerlab.org/teachopencadd/installing.html
The installation will become much easier next week I hope with a simple `mamba install teachopencadd` command.

> By the way, this would be more a debate that a question. Normally for predict endpoints (classification or regression problems doesn't matter), you use as a input, 2d descriptors of RDKIT or fingerprints, and I know that it is possible to obtain 3D information with rdkit and Also there are another libraries for obtaining fingerprints 3d. But for example with pharmacophore information and MDAanalysis that you work in your notebooks, for complement the information that previously I said you. what variables would you add (related with your notebooks of MDAanalysis and pharmacophore)? It is possible that the ML or DL models don't improve but It would be interesting check it...

Regarding the 3D descriptors these resources come to my mind. Unfortunately, I have no experience myself with how they improve ML/DL models.
https://oddt.readthedocs.io/en/latest/rst/oddt.html#module-oddt.shape
https://www.rdkit.org/docs/GettingStartedInPython.html#list-of-available-3d-descriptors

**Comment by PARODBE** [comment]
Thank you!

I have another question, in a part of the code you define the ligand such as:

ligand_resname = "IRE"
ligand = structure.select_atoms(f"resname {ligand_resname}")
pocket_center = (ligand.positions.max(axis=0) + ligand.positions.min(axis=0)) / 2
pocket_size = ligand.positions.max(axis=0) - ligand.positions.min(axis=0) + 5

In this part if you had a molecule generated by for example Generative Models which generate molecules artificially, How would your work them? I want to say if you molecule (your ligand) doesn't exhist in pdb?

This question could be interesting also for the first part of the code if you have a new proteing generated with alphafold...

Thanks!

**Comment by dominiquesydow** [comment]
Hi @PARODBE,

Could you please post your last question in our new Discussion section (incl. a note which talktorial you refer to)? https://github.com/volkamerlab/teachopencadd/discussions (Category Q&A)

We want to channel all discussions to that section, while reserving the issues only for bugs and feature requests. This helps us to organize ourselves better - and helps other people to find previously discussed topics more easily. Thank you!

I am closing this issue now, waiting for your post in Discussions, thank you!
