### ISSUE TITLE
T018 / website: NGLview 3D visualization not shown

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#194]
On our website, the T018 3D visualizations with NGLview are not shown. 

Compare 
https://projects.volkamerlab.org/teachopencadd/talktorials/T018_automated_cadd_pipeline.html#Processing-the-input-protein-data
to 3D view in 
https://projects.volkamerlab.org/teachopencadd/talktorials/T012_query_klifs.html#4.-Show-the-structure-with-nglview

**Comment by AndreaVolkamer** [comment]
@dominiquesydow they also do not show in the talktorial itself: https://nbviewer.org/github/volkamerlab/teachopencadd/blob/master/teachopencadd/talktorials/T018_automated_cadd_pipeline/talktorial.ipynb
Can you double check if they were shown on your local system before you pushed the notebook (I sometimes have trouble with nglview if i executed a notebook too many times ...).

**Comment by dominiquesydow** [comment]
I am on it now. I think on the new laptop I have not had "Save widget state automatically" ticked, yet. 
The 3D viz was there before I pushed but I think the state was not saved. Maybe --- hopefully --- this is all :)
