### ISSUE TITLE
can't this be hosted on a website?

### ISSUE THREAD

**Issue by UnixJunkie** [volkamerlab/TeachOpenCADD#2]
Hello,

It would be nice if people can have a quick look without having to install anything.

Regards,
F.

**Comment by dominiquesydow** [comment]
Hello!

Thank you for your feedback!

As for now, we suggest to use Binder to host the repository and all needed dependencies (and updated our usage instructions accordingly). 

That way you do not need to install anything locally.
You can follow this link ...
https://mybinder.org/v2/gh/volkamerlab/TeachOpenCADD/master
... and both the repository and packages are set up for you.

Note 1: Using Binder only works for talktorials T1-7 (T8-T10 are not stand-alone Jupyter notebooks, but also use PyMOL). 

Note 2: I experienced that the setup is often pretty fast, however in other cases it takes too long. 
So this solution might not be always useful for a quick look, but when working it is a very convenient way to circumvent local installation.

For a quick non-interactive look, you can also use GitHub to display the Jupyter notebooks (however admittedly also here sometimes the notebooks are not loaded immediately).

Kind regards,
Dominique

**Comment by UnixJunkie** [comment]
Cool, thanks!
