### ISSUE TITLE
T016: HTML rendering of list items

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#203]
Fix HTML rendering of list items:

> This dictionary is composed of two levels: - First level is the detected binding sites. - For each binding site, we have one more sub-dictionary containing eight lists, one for each specific interaction. * Each list will contain the column names in the first row, and the data (if available) in the following.

https://projects.volkamerlab.org/teachopencadd/talktorials/T016_protein_ligand_interactions.html#Profiling-protein-ligand-interactions-using-PLIP

**Comment by dominiquesydow** [comment]
And remove one indent level in docstrings:

```
    """
    Retrieves the interactions from PLIP.

    Parameters
    ----------
    pdb_file :
            The PDB file of the complex.  # Remove one indent level

    Returns
    -------
    dict :
            A dictionary of the binding sites and the interactions. # Remove one indent level
    """

```

**Comment by dominiquesydow** [comment]
data frame > DataFrame

**Comment by dominiquesydow** [comment]
`show_interactions_3D` > `show_interactions_3d`

**Comment by dominiquesydow** [comment]
`show_interactions_3D` - center on ligand!

**Comment by dominiquesydow** [comment]
Hi @t-kimber, would you have some capacity to take a look at this list of minor text issues I found in T016? Nothing urgent, notebook is fully functional!

**Comment by t-kimber** [comment]
Of course, thanks for spotting them. I also changed `viewer_3D`> `viewer_3d` to be consistent with `show_interactions_3d`.
