### ISSUE TITLE
Temporarily pin rdkit<=2021.09.2

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#204]
I am seeing this error in TeachOpenCADD and OpenCADD since yesterday(?):

```
AttributeError: module 'pandas.io.formats' has no attribute 'html'
```

https://github.com/volkamerlab/teachopencadd/runs/4542687313?check_suite_focus=true#step:8:63

Any help appreciated to track down the trouble-maker :) 
@t-kimber, @schallerdavid, @corey-taylor - any chance, any one of you has some time at their hands tomorrow to check this out?

**Comment by schallerdavid** [comment]
Sure, I will investigate, looks like a rdkit pandastools problem to me.

**Comment by dominiquesydow** [comment]
By now, RDKit is pinned to 2021.09.5, see https://github.com/volkamerlab/teachopencadd/issues/227 - closing this issue.
