### ISSUE TITLE
Talktorial 11b: Problems connecting to OPAL web services

### ISSUE THREAD

**Issue by simsurp** [volkamerlab/teachopencadd#21]
Hi.
Thank you very much for putting together these talktorials.  It's aweTsome !
I'm having issues connecting to the OPAL web services. The line ` client = Client("http://nbcr-222.ucsd.edu/opal2/services/vina_1.1.2?wsdl")` in the fonction `opal_run_docking(protein, ligand, center, size, stream_output=True)` is giving me an ExpatError and SAXParseException.
Any idea on how I could fix that?
Thanks again.

ExpatError                                Traceback (most recent call last)
~/anaconda3/envs/teachopencadd/lib/python3.6/xml/sax/expatreader.py in feed(self, data, isFinal)
    216             # except when invoked from close.
--> 217             self._parser.Parse(data, isFinal)
    218         except expat.error as e:

ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

SAXParseException                         Traceback (most recent call last)
<ipython-input-23-73d4876858b2> in <module>
      1 from suds.client import Client
----> 2 client = Client("http://nbcr-222.ucsd.edu/opal2/services/vina_1.1.2?wsdl")

**Comment by simsurp** [comment]
I just found this from the [NBCR website](http://nbcr.ucsd.edu/):
Please Note:  NBCR and its associated websites/services have been retired as of April 30, 2020.
Could that explain my problem?

**Comment by jaimergp** [comment]
Ooooh! Definitely!

Well, that means this notebook has only historic value for now :) We'll try to find a webservice alternative to run Vina. If you find something, please let us know! Thanks for the report!

**Comment by simsurp** [comment]
That’s sad.  Do you think that it could now work with SwissDock ?

De : Jaime Rodríguez-Guerra [mailto:notifications@github.com]
Envoyé : 4 mai 2020 03:43
À : volkamerlab/TeachOpenCADD <TeachOpenCADD@noreply.github.com>
Cc : Simon Surprenant <sims07@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [volkamerlab/TeachOpenCADD] Talktorial 11b: Problems connecting to OPAL web services (#21)


Ooooh! Definitely!

Well, that means this notebook has only historic value for now :) We'll try to find a webservice alternative to run Vina. If you find something, please let us know! Thanks for the report!

**Comment by jaimergp** [comment]
Last time I tried it wasn't working, but I didn't investigate more since we had OPAL anyway. Might be worth the try now, but I am a bit short of time lately... You can try [asking them](http://www.swissdock.ch/pages/soap_access) if the SOAP access is back online. If they reply affirmatively, I could help!

**Comment by jaimergp** [comment]
Possible alternative, PLIDFlow: https://pistacho.ac.uma.es/galaxy-bitlab/

**Comment by dominiquesydow** [comment]
As a heads-up: This issue will be closed automatically with the merge of #74. The docking part of the former 11b talkorial was moved to talktorial T015, which uses `smina` for docking.
