### ISSUE TITLE
T008: Current query misses existing RCSB ligands

### ISSUE THREAD

**Issue by BJWiley233** [volkamerlab/teachopencadd#248]
Hi,

For talktorial 8 for accessing RCSB I think RCSB is having issue with not having all the ligands under the field `["rcsb_entry_info"]["nonpolymer_bound_components"]`.  For instance I am using MAP2K1 but I'm for sure it will affect other proteins and for entry https://data.rcsb.org/rest/v1/core/entry/3ZLS there is only `["NA"]` value for `nonpolymer_bound_components` when the [structure](https://www.rcsb.org/structure/3ZLS) has '92P' as the largest ligand.  I found an alternative under `["pdbx_vrpt_summary"]["restypes_notchecked_for_bond_angle_geometry"]` so the following should work better as an alternative in talktorial 8.

```
nonpolymers = info.get("pdbx_vrpt_summary", {}).get('restypes_notchecked_for_bond_angle_geometry',[])
```

This is also kind of interesting to find out that most ligands are not checked for the bond angle geometry.  All the more reason to use [TinkerTools/poltype2](https://github.com/TinkerTools/poltype2) for ligand geometry optimization! 😄

**Comment by BJWiley233** [comment]
I have actually been using `graphQL` based on Rachel Green's advice at RSCB.  It works well and you don't need to make it a single line to work:
```
import urllib3
http = urllib3.PoolManager()
query = '''{
      entry(entry_id: "%s") {
        nonpolymer_entities {
          pdbx_entity_nonpoly {
            comp_id
            name
            rcsb_prd_id
          }
        }
      }
    }''' % pdb_id
    query_url='https://data.rcsb.org/graphql?query=%s' % query
    r = http.request('GET', query_url, preload_content=False)
    r.status
    my_json = json.loads(r.data)
```

**Comment by khanmf** [comment]
Hi @dominiquesydow ,

When I am running the same coddes for **pdb_id = '3POZ'**, it is giving the following error:

Traceback (most recent call last):
  File "PDB_Query.py", line 428, in <module>
    ligand_id, properties = max(ligands.items(), key=lambda kv: kv[1]["Molecular weight"])
ValueError: max() arg is an empty sequence

How this could be an empty sequence when there are two bound ligands 03P and SO4? Out of which 03P is the bigger one.

**Comment by dominiquesydow** [comment]
Did you pull the latest changes from the `master` branch already?

The updated `get_ligand` function
```python
get_ligands("3POZ")
``` 
returns the following:
```
{'SO4': {'Name': 'SULFATE ION',
  'Formula': 'O4 S',
  'Formal charge': -2,
  'Molecular weight': 96.063,
  'Component type': 'NON-POLYMER',
  'Atom count': 5,
  'Chiral atom count': 0,
  'Bond count': 4,
  'Aromatic bond count': 0,
  'Systematic name (ACDLabs)': 'sulfate',
  'Systematic name (OpenEye OEToolkits)': 'sulfate',
  'Stereo SMILES (CACTVS)': '[O-][S]([O-])(=O)=O',
  'SMILES (CACTVS)': '[O-][S]([O-])(=O)=O',
  'Stereo SMILES (OpenEye)': '[O-]S(=O)(=O)[O-]',
  'InChI descriptor': 'InChI=1S/H2O4S/c1-5(2,3)4/h(H2,1,2,3,4)/p-2',
  'InChIKey descriptor': 'QAOWNCQODCNURD-UHFFFAOYSA-L',
  'Last modified': '2011-06-04',
  'Created': '1999-07-08',
  'Release status': 'REL',
  'Replaces': 'SUL',
  'Model PDB code': '1BXO',
  'Processing site': 'RCSB'},
 '03P': {'Name': 'N-{2-[4-({3-chloro-4-[3-(trifluoromethyl)phenoxy]phenyl}amino)-5H-pyrrolo[3,2-d]pyrimidin-5-yl]ethyl}-3-hydroxy-3-methylbutanamide',
  'Synonyms': 'TAK-285',
  'Formula': 'C26 H25 Cl F3 N5 O3',
  'Formal charge': 0,
  'Molecular weight': 547.957,
  'Component type': 'NON-POLYMER',
  'Atom count': 63,
  'Chiral atom count': 0,
  'Bond count': 66,
  'Aromatic bond count': 22,
  'Systematic name (ACDLabs)': 'N-{2-[4-({3-chloro-4-[3-(trifluoromethyl)phenoxy]phenyl}amino)-5H-pyrrolo[3,2-d]pyrimidin-5-yl]ethyl}-3-hydroxy-3-methylbutanamide',
  'Systematic name (OpenEye OEToolkits)': 'N-[2-[4-[[3-chloranyl-4-[3-(trifluoromethyl)phenoxy]phenyl]amino]pyrrolo[3,2-d]pyrimidin-5-yl]ethyl]-3-methyl-3-oxidanyl-butanamide',
  'Stereo SMILES (CACTVS)': 'CC(C)(O)CC(=O)NCCn1ccc2ncnc(Nc3ccc(Oc4cccc(c4)C(F)(F)F)c(Cl)c3)c12',
  'SMILES (CACTVS)': 'CC(C)(O)CC(=O)NCCn1ccc2ncnc(Nc3ccc(Oc4cccc(c4)C(F)(F)F)c(Cl)c3)c12',
  'Stereo SMILES (OpenEye)': 'CC(C)(CC(=O)NCCn1ccc2c1c(ncn2)Nc3ccc(c(c3)Cl)Oc4cccc(c4)C(F)(F)F)O',
  'InChI descriptor': 'InChI=1S/C26H25ClF3N5O3/c1-25(2,37)14-22(36)31-9-11-35-10-8-20-23(35)24(33-15-32-20)34-17-6-7-21(19(27)13-17)38-18-5-3-4-16(12-18)26(28,29)30/h3-8,10,12-13,15,37H,9,11,14H2,1-2H3,(H,31,36)(H,32,33,34)',
  'InChIKey descriptor': 'ZYQXEVJIFYIBHZ-UHFFFAOYSA-N',
  'Last modified': '2021-03-01',
  'Created': '2010-11-30',
  'Release status': 'REL',
  'Model PDB code': '3POZ',
  'Processing site': 'RCSB'}}
```

**Comment by khanmf** [comment]
@dominiquesydow Thanks. I haven't seen the recent changes in the codes. Its working fine, now.
