### ISSUE TITLE
T008+T010: RCSB query 404 errors

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#252]
We see 404 HTML errors for RCSB queries in T008 and T010, e.g. T008 cell 5. 

```
---------------------------------------------------------------------------
RequestError                              Traceback (most recent call last)
Input In [5], in <cell line: 6>()
      1 query_by_uniprot_id = rcsb.FieldQuery(
      2     "rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers.database_accession",
      3     exact_match=uniprot_id,
      4 )
      5 today = datetime.datetime.now()
      6 print(
----> 7     f"Number of structures on {today.year}-{today.month}-{today.day}: {rcsb.count(query_by_uniprot_id)}"
      8 )

File ~/mambaforge/envs/toc-dev/lib/python3.9/site-packages/biotite/database/rcsb/query.py:498, in count(query, return_type)
    496 else:
    497     try:
--> 498         raise RequestError(f"Error {r.status_code}: {r.json()['message']}")
    499     except json.decoder.JSONDecodeError:
    500         # In case there an error response without message
    501         raise RequestError(f"Error {r.status_code}")

RequestError: Error 404: HTTP 404 Not Found
```

**UPDATE 2022-07-21: Update `biotite` to version 0.34.0 and the notebooks will run again under Python >= 3.8!**

**Comment by dominiquesydow** [comment]
RCSB did another API change, which will be picked up shortly in `biotite` - this should fix the CI fails we are seeing in TeachOpenCADD. See https://github.com/biotite-dev/biotite/issues/405.

**Comment by BJWiley233** [comment]
Nice catch :)

**Comment by dominiquesydow** [comment]
Thanks to the latest release of `biotite`(0.34.0), our `teachopencadd` tests are running again for Python 3.9:
https://github.com/volkamerlab/teachopencadd/runs/7445740051?check_suite_focus=true 🎉 

Under Python 3.7, we seem to be stuck with `biotite` 0.31.0, hence the tests are still failing. Why is this happening? Not sure.
- The `conda` recipe does no Python version pinning: https://github.com/conda-forge/biotite-feedstock/blob/main/recipe/meta.yaml
- However, the `biotite` release notes for 0.32.0 do mention that Python 3.7 builds are discontinued: https://github.com/biotite-dev/biotite/releases/tag/v0.32.0

---

To think about in the short-term:
- Try to find out why the `conda` package does not support Python 3.7 from version 0.32.0 although I cannot find a pinned Python version in the `conda` recipe --- @jaimergp do you have an idea?
- Drop `teachopencadd` support for Python 3.7?
- Definitely: Pin `biotite` version to 0.34.0 in the `teachopencadd`'s env and  `conda` recipe.

**Comment by jaimergp** [comment]
They are doing `skip: True` for Python < 3.8 in the build section.

I think it's ok if we bump our Python requirements to Python 3.8 and above. Otherwise we need to soft import biotite and error out gracefully indicating that Python 3.8+ is required for those notebooks.

**Comment by dominiquesydow** [comment]
Oh, yes, now I see it, too, thanks! (note to myself: [see this line](https://github.com/conda-forge/biotite-feedstock/blob/4cc79ddbaa7bbc70b9b893c4c2fc5d585f017124/recipe/meta.yaml#L16))

Bumping up our requirements to Python 3.8 in https://github.com/volkamerlab/teachopencadd/pull/254.
