### ISSUE TITLE
Resources on Jupyter notebooks

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#261]
Collect resources on how to use Jupyter notebooks - to be added to the TeachOpenCADD documentation:

- https://www.dataquest.io/blog/jupyter-notebook-tutorial/

**Comment by sbhong238** [comment]
Collect resources on how to use Jupyter notebooks - to be added to the TeachOpenCADD documentation:

https://www.dataquest.io/blog/jupyter-notebook-tutorial/

**Comment by Telomelonia** [comment]
@dominiquesydow 
Assign this issue to me, I will make the documentation in the .rst file for - "How to use Jupyter notebooks" and will add it to /docs.

**Comment by dominiquesydow** [comment]
@Telomelonia, thanks!!

I was thinking of adding a "Jupyter notebook tutorials" section here:
https://github.com/volkamerlab/teachopencadd/blob/master/docs/external_tutorials_collections.rst

Adding the following two links to the new section should be enough (one tutorial and one cheat sheet):
- https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Jupyter_Notebook_Cheat_Sheet.pdf
- https://www.dataquest.io/blog/jupyter-notebook-tutorial/

We can link to this new section in the installation instructions (step 4)
https://github.com/volkamerlab/teachopencadd/blob/master/docs/installing.rst
with something like "If you need an introduction to Jupyter notebooks, please check here <link to new section>".

Would you like to take this on?

**Comment by Telomelonia** [comment]
@dominiquesydow

Ohh nice ... That saves a lot of work will add the PR once done. ✌️

**Comment by Telomelonia** [comment]
@dominiquesydow 
I added the PR for the issue.
