### ISSUE TITLE
T022: Missing import GetMorganFingerprintAsBitVect

### ISSUE THREAD

**Issue by mbackenkoehler** [volkamerlab/teachopencadd#289]
T022 is missing the import of 
```python
from rdkit.Chem.rdMolDescriptors import GetMorganFingerprintAsBitVect
```
which is used in `smiles_to_fp`.

**Comment by dominiquesydow** [comment]
Thanks for spotting this!

TODO: We are using 

```
from rdkit.Chem.AllChem import GetMorganFingerprintAsBitVect
```

in [T007](https://projects.volkamerlab.org/teachopencadd/talktorials/T007_compound_activity_machine_learning.html) --- check which of these two imports we should go for.

**Comment by dominiquesydow** [comment]
```python
from rdkit.Chem.AllChem import GetMorganFingerprintAsBitVect
```
still seems to be the default import, while

```python
from rdkit.Chem.rdMolDescriptors import GetMorganFingerprintAsBitVect
```

is useful for advanced usage, see:
https://www.rdkit.org/docs/GettingStartedInPython.html#morgan-fingerprints-circular-fingerprints
