### ISSUE TITLE
Update notebooks to `pandas`2.0.0

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#328]
`pandas` 2.0.0 does not allow `Series.append` anymore - use `concat` instead AFAIU.

@AndreaVolkamer, could you please ask around in your group if anyone is free to do some `pandas` 2.0.0 updates?
Should only concern the `plot_radar` function in T002. Thank you!

EDIT: See e.g. CI https://github.com/volkamerlab/teachopencadd/actions/runs/4654071089/jobs/8235487168#step:8:90

**Comment by AndreaVolkamer** [comment]
@mbackenkoehler can you please have a look at this.
