### ISSUE TITLE
CI: New pandas formatting?

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#329]
CI shows a lot of `pandas` diffs like this:

```
  '            ...    220.224  ' == '            ...    220.224  '
  Skipping 65 identical leading characters in diff, use -v to show
  Skipping 720 identical trailing characters in diff, use -v to show
  -     name   
  ?           ^
  +     name  \
  ?           ^
  - 0  CC1C2C(C3C(C(=O)C(=C(C3(C(=O)C2=C(C4=C1C=CC=C4...          Doxycycline  \
  ?                                                                            ^
  + 0  CC1C2C(C3C(C(=O)C(=C(C3(C(=O)C2=C(C4=C1C=CC=C4...          Doxycycline   
  ?                                                                            ^
    6  CC1(C
```
https://github.com/volkamerlab/teachopencadd/actions/runs/4654071089/jobs/8235487168#step:8:153

Looks like an updated pandas formatting but have not looked into this at all, yet, just reporting this as a reminder for us.
@AndreaVolkamer, is anyone in your group free to take a look at what is going on here?

**Comment by AndreaVolkamer** [comment]
@mbackenkoehler can you please also have a look at this? Solving both issues should turn the CI light green again.
