### ISSUE TITLE
Docs CI fails

### ISSUE THREAD

**Issue by mbackenkoehler** [volkamerlab/teachopencadd#333]
Currently, the Docs CI fails on the Sphinx 404 checks. Take [this one](https://github.com/volkamerlab/teachopencadd/actions/runs/4717016503/jobs/8365247063), for example.

![image](https://user-images.githubusercontent.com/14641050/234371813-ba247bd7-48f4-46a7-a77a-44b63f4e4119.png)

@dominiquesydow Any ideas for a quick fix?

**Comment by dominiquesydow** [comment]
Hi @mbackenkoehler, 

It seems like the URL checker that we have been using here (`broken-link-checker`) is no longer maintained:
```
npm WARN exec The following package was not found and will be installed: broken-link-checker@0.7.8
npm WARN deprecated calmcard@0.1.1: no longer maintained
npm WARN deprecated nopter@0.3.0: try optionator
npm WARN deprecated urlobj@0.0.11: use universal-url, minurl, relateurl, url-relation
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Error: Unhandled Rejection. Error: connect ECONNREFUSED ::1:8000
Error: Process completed with exit code 1.
`
``

Could you please try either the proposed package in the error message --- or try ´linkinator´ which we are using for our lab website:
https://github.com/volkamerlab/volkamerlab_org/blob/482d6cb15f4406c1b1863123efe8d5b294c1f7cd/.github/workflows/ci.yaml#L33

**Comment by mbackenkoehler** [comment]
I switched to `linkinator`. This seems to work fine. (see #335 )

However, there are a quite a few dead links right now. I will open an separate issue for that.

**Comment by mbackenkoehler** [comment]
Docs CI fixed.
