### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by mbackenkoehler** [volkamerlab/teachopencadd#336]
As per the CI, the following links do not work. The 403 are rejections which can probably be added to the skips like `doi.org`. The 404 either moved or are gone. These need to be fixed manually.
  

- [x]  [404] _static/images/apple-icon-152x152.png
## external_dependencies.html
- [x]   [404] http://rasbt.github.io/biopandas/
##  external_tutorials_collections.html
- [x] #342
- [x]   [404] https://psychiatrie-psychotherapie.charite.de/metas/person/person/address_detail/ritter-7/
## talktorials/T004_compound_similarity.html
- [x]   [403] http://pubs.acs.org/doi/abs/10.1021/jm401411z
## talktorials/T005_compound_clustering.html
- [x]  [404] talktorials/images/butina_full.pdf
## talktorials/T011_query_online_api_webservices.html
- [x]   [404] talktorials/data/_tmp/video.mp4
- [x]   [0] https://2.python-requests.org/en/master/user/quickstart/
- [x]   [0] https://2.python-requests.org/en/master/user/authentication/
## talktorials/T012_query_klifs.html
- [x]  [403] https://www.science.org/doi/10.1126/science.1075762
## talktorials/T013_query_pubchem.html
- [x]   [0] http://www.icoa.fr/pkidb/
- [x]  https://www.icoa.fr/pkidb/index.html
##  talktorials/T015_protein_ligand_docking.html
- [x]   [403] https://www.schrodinger.com/training/videos/small-molecule-drug-discovery/introduction-drugs-drug-targets-and-molecular
- [x]   [403] https://www.schrodinger.com/training/videos/small-molecule-drug-discovery/protein-ligand-docking
- [x]   [404] http://autodock.scripps.edu/faqs-help/faq/what-is-the-format-of-a-pdbqt-file
- [x]   [404] http://vina.scripps.edu/manual.html
## talktorials/T022_ligand_based_screening_neural_network.html
- [x]   [403] https://machinelearningmastery.com/rectified-linear-activation-function-for-deep-learning-neural-networks/
- [x]   [403] https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/
- [x]   [403] https://machinelearningmastery.com/adam-optimization-algorithm-for-deep-learning/
- [x]   [410] https://xzz201920.medium.com/activation-functions-linear-non-linear-in-deep-learning-relu-sigmoid-softmax-swish-leaky-relu-a6333be712ea
##  talktorials/T021_one_hot_encoding.html
- [x]   [403] https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/
- [x]   [0] https://www.machinecurve.com/index.php/2020/02/07/what-is-padding-in-a-neural-network/
## talktorials/T009_compound_ensemble_pharmacophores.html
- [x]   [403] http://pubs.acs.org/doi/pdf/10.1021/ci049885e
## talktorials/T012_query_klifs.html
- [x]   [403] https://science.sciencemag.org/content/298/5600/1912
- [x]   [403] https://www.science.org/doi/10.1126/science.1075762
## talktorials/T018_automated_cadd_pipeline.html
- [x]  [404] http://rasbt.github.io/biopandas/
- [x]  [404] http://vina.scripps.edu/manual.html
## talktorials/T020_md_analysis.html
- [x]   [404] https://www.mdanalysis.org/docs/documentation_pages/analysis/hbond_analysis.html

**Comment by mbackenkoehler** [comment]
@hamzaibrahim21 You can tick off the links you worked through here.

**Comment by hamzaibrahim21** [comment]
All links should be fixed except for the first error " [404] _static/images/apple-icon-152x152.png". Should I add an "apple-icon-152x152.png", because there is no such an image in mentioned directory, or just ignore the error?

**Comment by mbackenkoehler** [comment]
@hamzaibrahim21 That's great! Thanks! Yes, please add the appli-icon one. It should be safe to ignore.

**Comment by mbackenkoehler** [comment]
@hamzaibrahim21 Somehow a few new ones popped up for me. You can run the checks locally, following the job in [the gh workflow](https://github.com/volkamerlab/teachopencadd/blob/fix-dead-links/.github/workflows/docs.yml).

Also, for local files you can check in `docs/_build.html` if everything built correctly. T005 is missing the butina figure, for example.

**Comment by hamzaibrahim21** [comment]
@mbackenkoehler All broken links are fixed by now [38709b2](https://github.com/volkamerlab/teachopencadd/pull/341/commits/38709b2c99155f5e5715f9f2727ad32cefb560c4), please let me know if other links popped up again.
