### ISSUE TITLE
[DL Edition] Add datamol dependency

### ISSUE THREAD

**Issue by mbackenkoehler** [volkamerlab/TeachOpenCADD#339]
Add datamol from channel `conda-forge` to the environment. This is needed in the molecular description talktorial T033.

**Comment by mbackenkoehler** [comment]
@gerritgr Have you found another solution?

**Comment by AndreaVolkamer** [comment]
@mbackenkoehler I did suggest a version without the datamol dependency: PR https://github.com/volkamerlab/teachopencadd/pull/351
[Note: I broke the notebook while solving merge conflicts, I still need to fix this)
