### ISSUE TITLE
TeachOpenCADD as Jupyter Book?

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#34]
Explore Jupyter Book to render TeachOpenCADD Jupyter Notebooks: 

- https://blog.jupyter.org/announcing-the-new-jupyter-book-cbf7aa8bc72e
- https://jupyterbook.org/intro.html
- https://jupyterbook.org/start/build.html

Also, maybe use this Scientific Python introduction for talktorial `017` (rendered with Jupyter Book)?
https://python-programming.quantecon.org/index_toc.html

**Comment by jaimergp** [comment]
Worth a deeper look in the future, for sure. Do you think it's something that'd replace our current plans or just an addition on top of the current efforts?

**Comment by dominiquesydow** [comment]
I am closing this issue now, since we are not planning to set up a Jupyter Book in the foreseeable future (we have the website instead).
