### ISSUE TITLE
Talktorial 4 - mistake in calculating experimental EF

### ISSUE THREAD

**Issue by rhjohnstone** [volkamerlab/TeachOpenCADD#35]
In the function `print_data_ef` in cell 46, we need to convert the inputted percentage `perc_ranked_dataset` into a fraction to successfully compare with the values in `enrich_df`.

Also, in cell 47, when using the concatenated dataframe `enrich_df`, the function `print_data_ef` takes the last line to find the relevant fraction, so will always choose whichever similarity measure was second in the concatenation (in cell 43). Instead, I think we should just compute the EF for each similarity measure separately.

**Comment by dominiquesydow** [comment]
@rhjohnstone, thank you a lot for catching this! We will merge your PR #36 as-is in a moment.
