### ISSUE TITLE
Talktorial template

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/teachopencadd#41]
# How to start

Replace example names as needed:

```
git clone https://github.com/volkamerlab/teachopencadd.git
cd teachopencadd/
# or... git pull on master
git checkout -b ab-099-title  # ab = your initials; 099 = your talktorial index; title = short talktorial title 
git commit --allow-empty -m "Start branch"
git push --set-upstream origin ab-099-title

# Now go to the suggested URL and create the PR using the suggested template
# If the template is not there, copy it from this issue: https://github.com/volkamerlab/TeachOpenCADD/issues/41

# Back to the CLI to set up the environment
conda env create -f devtools/conda-envs/test_env.yml
conda activate teachopencadd
jupyter labextension install @ijmbarr/jupyterlab_spellchecker
jupyter lab
```
Now you can start working on your talktorial!

# Render the website locally

Once your talktorial ready, check how it renders in HTML.

```
cd docs
make html
cp -r talktorials/images/ _build/html/talktorials/images
cd _build/html
# open index.html on your browser:
xdg-open index.html
# or under windows: explorer.exe index.html
# or under MacOS: open index.html
```
If your notebook does not appear, you need to add the `nblink` forwarder in `docs/notebooks`. Copy paste an existing ones and update paths accordingly!

# PR template

Create a PR using this template. Ping us as reviewer once you'd like feedback on the talktorial. 

https://github.com/volkamerlab/teachopencadd/blob/master/.github/PULL_REQUEST_TEMPLATE/talktorial_review.md

**Comment by dominiquesydow** [comment]
I added:

Content review:

* [ ] The table of contents reflects the talktorial story-line and is hierarchically correct (check order of #, ##, ### headers)
* [ ] I have spell-checked the notebook
* [ ] I have checked that cell outputs are not too long (not more than 30 lines; this applies also to `DataFrames`)
* [ ] Markdown cell content is still in-line with code cell output (whenever results are discussed)
* [ ] I have marked all code cell whose output is referenced in markdown cells with the label `# TODO: CI`

**Comment by dominiquesydow** [comment]
Do we want everyone to push only notebooks without executed cells, @jaimergp? If so, we should add this to the checklist.

**Comment by jaimergp** [comment]
It's ok for now. We'll clear everything before merge anyway!

**Comment by t-kimber** [comment]
Super nice, super clear! Love the template :) 

Just a note for MAC users:
in the **Render the website locally** section, the command which will render the website is `open index.html` (and not `xdg-open index.html`).

**Comment by t-kimber** [comment]
What do you think if we add to the checklist a bullet point concerning populating the README.md in each talktorial folder (title, aim, learning goals, categories) ?

**Comment by jaimergp** [comment]
> What do you think if we add to the checklist a bullet point concerning populating the README.md in each talktorial folder (title, aim, learning goals, categories) ?

This is going to be automated with a little script. Do take a look at `<Talktorial>/data/README.md`, tho 😬

**Comment by t-kimber** [comment]
Just a small detail:

since the _reviews_ branch no longer exists, it might be an idea to change the todo list with _package_ , e.g. `git checkout package` instead of `git checkout reviews`?

**Comment by dominiquesydow** [comment]
Thanks, @jaimergp, for updating the template for the next round of talktorial refactoring :)
