### ISSUE TITLE
CI: don't forget adding more notebooks to `treebeard.yaml`

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/teachopencadd#63]
As we open PRs, these need to add their new notebooks to `treebeard.yaml`. This won't be needed _once_ the existing notebooks in tree have been processed. This involves minor changes to the CI pipelines so we just `ls` the directory instead of cherry picking which notebooks have to undergo testing.

**Comment by dominiquesydow** [comment]
Closing this issue since we are not using `treebeard` anymore.
