### ISSUE TITLE
RDKit and pypdb are pinned to old releases - update relevant notebooks

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/teachopencadd#77]
Last nightly contained a change in the Python 3.9 branch: T002 is reporting a different subset of compounds (just one entry, though).

https://github.com/volkamerlab/teachopencadd/runs/1461859605?check_suite_focus=true#step:8:47

Might be temporary (if the database was changing, it should affect all branches), so we'll wait until tomorrow to see if that's the case.

This nightly also reported a [bug in RDKit (py39)](https://github.com/volkamerlab/teachopencadd/runs/1461859605?check_suite_focus=true#step:8:376), in the `cairo` code to export images. Might be related to the same error as above (`Image` has changed API?). We'll wait too.

**Comment by jaimergp** [comment]
Interestingly the py39 branch is silently a py38 because the env resolution can only work through a python downgrade... 🤔 Trying to reproduce locally, but this might be a problem with `setup-miniconda`. Makes you wonder why this is failing to begin with, if the real py38 branch is indeed working 🤣

**Comment by jaimergp** [comment]
Using this issue to track problems seen in #78 

We are pinning RDKit to `>=2018.09.2.0,<2020.09.2` and `pypdb` to `1.*` for now. We'll address the unpinning in a new PR in the future.

**Comment by dominiquesydow** [comment]
Did the pinning happen? 

CI (PR for `master` < `pin-jlab2`) installs `rdkit` 2020.09.3 (check [CI report](https://github.com/volkamerlab/teachopencadd/pull/89/checks?check_run_id=1682290494#step:6:277)) and `pypdb` 2.0 (check [CI report](https://github.com/volkamerlab/teachopencadd/pull/89/checks?check_run_id=1682290494#step:6:256)).

**Comment by jaimergp** [comment]
Looks like I never worked on https://github.com/volkamerlab/teachopencadd/pull/78 as intended 😬
