### ISSUE TITLE
Update `pypdb`-related notebooks T008 and T010

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/teachopencadd#90]
`pypdb`-related notebooks must be updated since the old API does not work any more due to changes in the RCSB API.

From `pypdb`'s GH page:

> As of November 2020, pypdb is undergoing significantly refactoring in order to accomodate changes to the RCSB PDB API and extend functionality. We regret any breaking changes that occur along the way. The previous version of pypdb is available here; however, it will no longer function to to the RCSB API being 

Check out the new API:
https://github.com/williamgilpin/pypdb/blob/master/demos/demos.ipynb

---

__Example issue in T010__: 

Input:
```python
# Set up query dictionary
search_dict = pypdb.make_query("STI")
search_dict
```
Output:
```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-521e3a31d168> in <module>
      1 # Set up query dictionary
----> 2 search_dict = pypdb.make_query("STI")
      3 search_dict
AttributeError: module 'pypdb' has no attribute 'make_query'
```

**Comment by dominiquesydow** [comment]
Affects T008 and T010.

**Comment by dominiquesydow** [comment]
The only option I see is updating these two talktorials to the latest `pypdb` API. Do you agree, @jaimergp? I am volunteering to do that.

**Comment by dominiquesydow** [comment]
Discussed also in https://github.com/volkamerlab/teachopencadd/pull/89 (not linking it because that PR is initially only about pinning JLab 2).

**Comment by jaimergp** [comment]
Moving to the latest `pypdb` API is definitely the way forward. If you have the bandwidth, feel free to go ahead! Ping me as needed, of course!

**Comment by dominiquesydow** [comment]
> Moving to the latest pypdb API is definitely the way forward. If you have the bandwidth, feel free to go ahead! Ping me as needed, of course!

Just to make sure I do not misunderstand the `pypdb` issue - we cannot use the 1.* versions any more because the old RCSB API is not supported any more. Meaning, we _have_ to update to the newest `pypdb` API, correct?

**Comment by jaimergp** [comment]
Unfortunately, that's the case, yes. Read more [here](https://github.com/williamgilpin/pypdb/issues/16).

**Comment by dominiquesydow** [comment]
Some functionalities are not yet available via `pypdb` yet, which we use in our notebooks.
Example for T010 - fetch all Imatinib-bound structures.

Maybe this will help to set up a workaround?
https://asciieg.wordpress.com/

**Comment by jaimergp** [comment]
We can also write some functions for the REST API and use those directly, bypassing `pypdb` entirely.

**Comment by dominiquesydow** [comment]
Took a look at T010 again.

**What we want**

Get the PDB IDs of all structures that are bound to some query ligand (e.g. STI).

---

**Problem**

We were using 
```python
pypdb.make_query("STI")
```
to search for structures bound to STI. This method is not available any more in `pypdb` since RCSB made their API changes. 

---

**Attempt 1**

I looked around the `pypdb` package to find something similar, the only thing I found is this but it is not working yet:
https://github.com/williamgilpin/pypdb/blob/master/pypdb/clients/search/EXAMPLES.md#search-for-calcium-bound-calmodulin-structures
`pypdb.clients.search.search_client.perform_search_with_graph` but something is not ready here:

```python
from pypdb.clients.search.search_client import perform_search_with_graph
from pypdb.clients.search.search_client import ReturnType
from pypdb.clients.search.search_client import QueryGroup, LogicalOperator
from pypdb.clients.search.operators import text_operators


is_in_complex_with_calcium = text_operators.ExactMatchOperator(
    attribute="rcsb_chem_comp_container_identifiers.comp_id",
    value="CA"
)

results = perform_search_with_graph(
  query_object=QueryGroup(
    logical_operator=LogicalOperator.AND,
    queries=[is_in_complex_with_calcium]
  ),
  return_type=ReturnType.ENTRY
)
```
throws
```
AttributeError: 'ExactMatchOperator' object has no attribute '_validate'
```
I am abandoning this for now.

---

**Attempt 2**

Other idea was to use the PDB API directly but I am failing to put together the correct URL.

I do not think what we need is currently exposed in the [RCSB RESTful API](https://data.rcsb.org/redoc/index.html):

- https://data.rcsb.org/rest/v1/core/chemcomp/STI will give us ligand information for STI
- https://data.rcsb.org/rest/v1/core/entry/3poz will give us information about a structure

but how to query for structures based on some criteria ([results when using the PDB website manually](https://www.rcsb.org/search?request=%7B%22query%22%3A%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22group%22%2C%22logical_operator%22%3A%22and%22%2C%22nodes%22%3A%5B%7B%22type%22%3A%22terminal%22%2C%22service%22%3A%22text%22%2C%22parameters%22%3A%7B%22operator%22%3A%22in%22%2C%22negation%22%3Afalse%2C%22value%22%3A%5B%22STI%22%5D%2C%22attribute%22%3A%22rcsb_chem_comp_container_identifiers.comp_id%22%7D%2C%22node_id%22%3A0%7D%5D%7D%5D%2C%22label%22%3A%22text%22%7D%5D%2C%22label%22%3A%22query-builder%22%7D%2C%22return_type%22%3A%22entry%22%2C%22request_options%22%3A%7B%22pager%22%3A%7B%22start%22%3A0%2C%22rows%22%3A25%7D%2C%22scoring_strategy%22%3A%22combined%22%2C%22sort%22%3A%5B%7B%22sort_by%22%3A%22score%22%2C%22direction%22%3A%22desc%22%7D%5D%7D%2C%22request_info%22%3A%7B%22src%22%3A%22ui%22%2C%22query_id%22%3A%227a00e565f783a6dd87902c172d84fcb4%22%7D%7D))?

---

**And now?**

@jaimergp, @AndreaVolkamer - shall I reach out to the RCSB support team in order to get some help here?

Last resort could be to manually add the PDB list from the manual PDB website query to the notebook with a big disclaimer that this notebook no longer works out of the box for other systems.

**Comment by AndreaVolkamer** [comment]
@dominiquesydow not sure if the answer is in there, but @schallerdavid also investigated in that direction in PLIP-related project ([here](https://github.com/volkamerlab/plipify/blob/project03/projects/03/main.ipynb)).

**Comment by schallerdavid** [comment]
@dominiquesydow maybe biotite would be an option here, but also with this tool I had limitations to get ligand information. I can investigate this but I may not have time for this in the next couple of days.

**Comment by schallerdavid** [comment]
@dominiquesydow ,

I found a solution for your problem using biotite:

```
import biotite.database.rcsb as rcsb
query_by_ligand_id = rcsb.FieldQuery(
    "rcsb_nonpolymer_entity_container_identifiers.nonpolymer_comp_id",
    exact_match="STI"
)
results = rcsb.search(query_by_ligand_id)
```

The `results` contains 27 pdb ids which matches to the number when querying the pdb manually.

**Comment by schallerdavid** [comment]
Btw, you can search this [website](https://search.rcsb.org/search-attributes.html) to find attributes you want to query for. The only problem left is, that you can only retrieve PDB codes right now. Querying a pdb code as an attribute to retrieve all co-crystallized expo ids is currently not possible. But I think this is more a problem on the PDB API site. If you are interested on how to still get such information, you can check the notebook Andrea linked above.

**Comment by dominiquesydow** [comment]
@schallerdavid, thanks a lot, this is super helpful!!

**Comment by dominiquesydow** [comment]
T010 issues are solved (using `biotite` instead of `pypdb` to query PDB IDs matching a list of criteria). This issue will close with the merge of #74.

**Comment by TolgaCorbaci** [comment]
T008 has similar problem
AttributeError: module 'pypdb' has no attribute 'get_ligands'

**Comment by dominiquesydow** [comment]
Hi @TolgaCorbaci, thank you for your report! We have now fixed talktorials T008 and T010 in PR https://github.com/volkamerlab/teachopencadd/pull/74 but we'll need a bit more time to merge it. If you'd like to start working with them right away you could checkout branch `t011-base` (note that this is a branch with quite some activity at the moment, notebooks still undergo changes).

**Comment by jaimergp** [comment]
@dominiquesydow should we use `biotite` on T008 too?

**Comment by dominiquesydow** [comment]
>@dominiquesydow should we use biotite on T008 too?

Thought about it as well. Would be definitely easier to read since it needs less code. You want me to take over?

Side note: `pypdb` mention in this context still needs to be removed.
>Since we will create ensemble ligand-based pharmacophores in the next talktorial, we remove all PDB structures from our DataFrame, which do not contain a bound ligand: we use the pypdb function get_ligands to check/retrieve the ligand(s) from a PDB structure. PDB-annotated ligands can be ligands, cofactors, but also solvents and ions. In order to filter only ligand-bound structures, we (i) remove all structures without any annotated ligand and (ii) remove all structures that do not contain any ligands with a molecular weight (MW) greater than 100 Da (Dalton), since many solvents and ions weight less. Note: this is a simple, but not comprehensive exclusion of solvents and ions.

**Comment by jaimergp** [comment]
> You want me to take over?

Please 🙏

**Comment by dominiquesydow** [comment]
T008 and T010 are now both ready. Will be merged into `master` with PR #42.

**Comment by Carlbullish** [comment]
Hi guys. Please has the pypdb query issue for T008 been fixed? i'm still having a problem with the error at get_ligands

**Comment by Carlbullish** [comment]
I am also having issues with this line could this be checked into?
results = align(complexes, method=METHODS["mda"])

this is the error i  keep getting. 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-75600e02e635> in <module>()
----> 1 results = align(complexes, method=METHODS["mda"])

4 frames
/usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/api.py in align(structures, method, **kwargs)
     40     results = []
     41     for mobile in mobiles:
---> 42         result = aligner.calculate([reference, mobile])
     43         results.append(result)
     44 

/usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/base.py in calculate(self, structures, *args, **kwargs)
     29         """
     30         assert len(structures) == 2
---> 31         return self._calculate(structures, *args, **kwargs)
     32 
     33     def _calculate(self, structures, *args, **kwargs):

/usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/mda.py in _calculate(self, structures, *args, **kwargs)
    117 
    118         # Get matching atoms
--> 119         selection, alignment = self.matching_selection(*structures)
    120         ref_atoms = ref_universe.select_atoms(selection["reference"])
    121         mobile_atoms = mob_universe.select_atoms(selection["mobile"])

/usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/mda.py in matching_selection(self, reference, mobile)
    182                 ref_segids=ref_segids,
    183                 target_segids=mob_segids,
--> 184                 backbone_selection=self.per_residue_selection,
    185             )
    186         return selection, alignment

/usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/sequences.py in fasta2select(fastafilename, ref_resids, ref_segids, target_resids, target_segids, backbone_selection)
    115 
    116     """
--> 117     protein_gapped = Bio.Alphabet.Gapped(Bio.Alphabet.IUPAC.protein)
    118     with open(fastafilename) as fasta:
    119         alignment = Bio.AlignIO.read(fasta, "fasta", alphabet=protein_gapped)

AttributeError: module 'Bio' has no attribute 'Alphabet'

**Comment by dominiquesydow** [comment]
> Hi guys. Please has the pypdb query issue for T008 been fixed? i'm still having a problem with the error at get_ligands

Hi @Carlbullish, thank you for the reminder. We have fixed the `pypdb`-based talktorials T008 and T010 in branch `t011-base`. We had to replace some `pypdb` functionalities with `biotite`. The changes are still stuck in a larger PR (https://github.com/volkamerlab/teachopencadd/pull/74); let me pull them to `master` later today. 

If you'd like to start right away, please checkout the branch `t011-base`.

**Comment by dominiquesydow** [comment]
> I am also having issues with this line could this be checked into?
> results = align(complexes, method=METHODS["mda"])
> 
> ## this is the error i keep getting.
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 results = align(complexes, method=METHODS["mda"])
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/api.py in align(structures, method, **kwargs)
> 40 results = []
> 41 for mobile in mobiles:
> ---> 42 result = aligner.calculate([reference, mobile])
> 43 results.append(result)
> 44
> 
> /usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/base.py in calculate(self, structures, *args, **kwargs)
> 29 """
> 30 assert len(structures) == 2
> ---> 31 return self._calculate(structures, *args, **kwargs)
> 32
> 33 def _calculate(self, structures, *args, **kwargs):
> 
> /usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/mda.py in _calculate(self, structures, *args, **kwargs)
> 117
> 118 # Get matching atoms
> --> 119 selection, alignment = self.matching_selection(*structures)
> 120 ref_atoms = ref_universe.select_atoms(selection["reference"])
> 121 mobile_atoms = mob_universe.select_atoms(selection["mobile"])
> 
> /usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/engines/mda.py in matching_selection(self, reference, mobile)
> 182 ref_segids=ref_segids,
> 183 target_segids=mob_segids,
> --> 184 backbone_selection=self.per_residue_selection,
> 185 )
> 186 return selection, alignment
> 
> /usr/local/lib/python3.7/dist-packages/opencadd/structure/superposition/sequences.py in fasta2select(fastafilename, ref_resids, ref_segids, target_resids, target_segids, backbone_selection)
> 115
> 116 """
> --> 117 protein_gapped = Bio.Alphabet.Gapped(Bio.Alphabet.IUPAC.protein)
> 118 with open(fastafilename) as fasta:
> 119 alignment = Bio.AlignIO.read(fasta, "fasta", alphabet=protein_gapped)
> 
> AttributeError: module 'Bio' has no attribute 'Alphabet'

Cross-referencing this to: https://github.com/volkamerlab/teachopencadd/issues/108
